SET NAMES utf8mb4;
SELECT COLUMN_NAME, COLUMN_COMMENT
FROM information_schema.COLUMNS
WHERE TABLE_NAME='solar_history' AND TABLE_SCHEMA='solardata'
ORDER BY ORDINAL_POSITION
INTO OUTFILE '/tmp/cc.txt'
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';
