SET NAMES utf8mb4;

ALTER TABLE solar_history
  COMMENT = 'ข้อมูลประวัติโซลาร์ทุก 5 นาที จาก Solarman API',
  MODIFY COLUMN station_id       BIGINT      NOT NULL         COMMENT 'Station ID จาก Solarman',
  MODIFY COLUMN station_name     VARCHAR(100) NOT NULL        COMMENT 'ชื่อสถานี',
  MODIFY COLUMN recorded_at      DATETIME    NOT NULL         COMMENT 'เวลาของ data point (Asia/Bangkok)',
  MODIFY COLUMN generation_power DOUBLE      DEFAULT 0        COMMENT 'กำลังผลิตโซลาร์ขณะนั้น (W)',
  MODIFY COLUMN battery_power    DOUBLE      DEFAULT 0        COMMENT 'กำลังแบต: ลบ=กำลังชาร์จ บวก=คายประจุ (W)',
  MODIFY COLUMN battery_soc      DOUBLE      DEFAULT 0        COMMENT 'ระดับพลังงานในแบตเตอรี่ (%)',
  MODIFY COLUMN charge_power     DOUBLE      DEFAULT 0        COMMENT 'กำลังที่ใช้ชาร์จแบต (W)',
  MODIFY COLUMN discharge_power  DOUBLE      DEFAULT 0        COMMENT 'กำลังที่คายจากแบต (W)',
  MODIFY COLUMN grid_power       DOUBLE      DEFAULT 0        COMMENT 'กำลังที่ export ไปกริด (W)',
  MODIFY COLUMN wire_power       DOUBLE      DEFAULT 0        COMMENT 'โหลดไฟฟ้าในบ้านทั้งหมด (W)',
  MODIFY COLUMN use_power        DOUBLE      DEFAULT 0        COMMENT 'พลังงานที่บ้านใช้จริงขณะนั้น (W)',
  MODIFY COLUMN purchase_power   DOUBLE      DEFAULT 0        COMMENT 'กำลังที่ซื้อจากการไฟฟ้า/นำเข้ากริด (W)',
  MODIFY COLUMN generation_value DOUBLE      DEFAULT 0        COMMENT 'พลังงานที่ผลิตสะสมวันนั้น (kWh)',
  MODIFY COLUMN buy_value        DOUBLE      DEFAULT 0        COMMENT 'พลังงานที่ซื้อจากกริดสะสม (kWh)',
  MODIFY COLUMN use_value        DOUBLE      DEFAULT 0        COMMENT 'พลังงานที่ใช้สะสม (kWh)',
  MODIFY COLUMN charge_value     DOUBLE      DEFAULT 0        COMMENT 'พลังงานชาร์จแบตสะสม (kWh)',
  MODIFY COLUMN discharge_value  DOUBLE      DEFAULT 0        COMMENT 'พลังงานคายแบตสะสม (kWh)',
  MODIFY COLUMN grid_value       DOUBLE      DEFAULT 0        COMMENT 'พลังงาน export ไปกริดสะสม (kWh)',
  MODIFY COLUMN generation_ratio DOUBLE      DEFAULT 0        COMMENT 'อัตราผลิตเทียบ capacity (%)',
  MODIFY COLUMN pr               DOUBLE      DEFAULT 0        COMMENT 'Performance Ratio - ประสิทธิภาพระบบ (%)',
  MODIFY COLUMN cpr              DOUBLE      DEFAULT 0        COMMENT 'Capacity Performance Ratio',
  MODIFY COLUMN full_power_hours DOUBLE      DEFAULT 0        COMMENT 'จำนวนชั่วโมงผลิตเต็มกำลัง (h)',
  MODIFY COLUMN theoretical_gen  DOUBLE      DEFAULT 0        COMMENT 'พลังงานที่ควรผลิตได้ตามทฤษฎี (kWh)',
  MODIFY COLUMN irradiate        DOUBLE      DEFAULT 0        COMMENT 'ปริมาณรังสีแสงอาทิตย์สะสม (kWh/m²)',
  MODIFY COLUMN irradiate_intensity DOUBLE   DEFAULT 0        COMMENT 'ความเข้มแสงอาทิตย์ (W/m²)';
